[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

{%- set license_classifiers = {
    'MIT': 'License :: OSI Approved :: MIT License',
    'GPL-3.0-or-later': 'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
    'Apache-2.0': 'License :: OSI Approved :: Apache Software License',
    'BSD-3-Clause': 'License :: OSI Approved :: BSD License',
    'GPL-3.0-or-later-short': 'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
    'Apache-2.0-short': 'License :: OSI Approved :: Apache Software License',
} %}
[project]
name = "{{ cookiecutter.project_slug }}"
version = "{{ cookiecutter.version }}"
description = "{{ cookiecutter.project_short_description }}"
readme = "README.md"
requires-python = ">=3.5,<4.0"
{%- if cookiecutter.open_source_license in license_classifiers %}
license = {file = "LICENSE"}
{%- endif %}
keywords = "{{ cookiecutter.project_slug }}"
authors = [
    {name = "{{ cookiecutter.full_name.replace('\"', '\\\"') }}", email = "{{ cookiecutter.email }}"},
]
maintainers = [
    {name = "{{ cookiecutter.full_name.replace('\"', '\\\"') }}", email = "{{ cookiecutter.email }}"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
{%- if cookiecutter.open_source_license in license_classifiers %}
    "{{ license_classifiers[cookiecutter.open_source_license] }}",
{%- endif %}
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Typing :: Typed",
]
dependencies = [{%- if cookiecutter.command_line_interface|lower == 'click' %}'Click>=7.0',{%- endif %} ]

[project.optional-dependencies]
test = []

[project.urls]
homepage = "https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.github_repository_name }}"
# documentation = "https://readthedocs.org"
repository = "https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.github_repository_name }}"
# changelog = "https://github.com/me/spam/blob/master/CHANGELOG.md"

{%- if 'no' not in cookiecutter.command_line_interface|lower %}
[project.entry-points."console_scripts"]
{{ cookiecutter.project_slug }} = "{{ cookiecutter.project_slug }}.cli:main"
{%- endif %}

[tool.setuptools]
zip-safe = false

[tool.isort]
# @see https://github.com/timothycrosley/isort/issues/694#issuecomment-581246882
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = {{ cookiecutter.python_code_max_length_per_line }}
{%- if cookiecutter.python_code_max_length_per_line != '88' %}

# @see https://black.readthedocs.io/en/stable/pyproject_toml.html#configuration-format
[tool.black]
line-length = {{ cookiecutter.python_code_max_length_per_line }}
{%- endif %}
{%- if cookiecutter.pylint_docstring_min_length != '-1' %}

[tool.pylint.basic]
docstring-min-length = "{{ cookiecutter.pylint_docstring_min_length }}"
{%- endif %}
{%- if cookiecutter.python_code_max_length_per_line != '100' %}

[tool.pylint.format]
max-line-length = "{{ cookiecutter.python_code_max_length_per_line }}"
{%- endif %}

[tool.pylint.messages_control]
# bad-continuation: @see https://github.com/PyCQA/pylint/pull/3571
disable = ''',
    bad-continuation,
    '''

[tool.pylint.options]
# Since this rule against single responsibility principle.
# @see https://stackoverflow.com/questions/28722314/why-does-pylint-want-2-public-methods-per-class/40258006#40258006
min-public-methods = "1"
