[tool.isort]
# @see https://github.com/timothycrosley/isort/issues/694#issuecomment-581246882
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = {{ cookiecutter.python_code_max_length_per_line }}
{%- if cookiecutter.python_code_max_length_per_line != '88' %}

# @see https://black.readthedocs.io/en/stable/pyproject_toml.html#configuration-format
[tool.black]
line-length = {{ cookiecutter.python_code_max_length_per_line }}
{%- endif %}
{%- if cookiecutter.python_code_max_length_per_line != '100' %}

[tool.pylint.format]
max-line-length = "{{ cookiecutter.python_code_max_length_per_line }}"
{%- endif %}

[tool.pylint.messages_control]
# bad-continuation: @see https://github.com/PyCQA/pylint/pull/3571
disable = ''',
    bad-continuation,
    '''
