# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

branches:
  only:
    - master
    - master-yukihiko-shinoda

# command to run tests, e.g. python setup.py test
script: tox

# Jobs (with stages)
jobs:
  include:
    - stage: deploy
      script: pipenv run invoke docs
      before_script:
        - pip install pipenv
        - pipenv install --dev --skip-lock
      python: 3.8
      deploy:
        provider: pages
        local-dir: docs/_build
        skip-cleanup: true
        github-token: $GH_TOKEN
        keep-history: true
        on:
           branch: master
