[dependency-groups]
dev = [
    "autoflake",
    "bandit",
    "bump-my-version",
    # To test baked cli.py
    # 2025-06-15: Since the latest Semgrep depends on click<8.2.dev0,
    # otherwise too legacy version of click is installed and it can't run in Windows.
    "click<8.2.0",
    "cohesion",
    # The coverage==3.5.3 is difficult to analyze its dependencies by dependencies management tool,
    # so we should avoid 3.5.3 or lower.
    # - Command: "pipenv install --skip-lock" fails 
    #   since it tries to parse legacy package metadata and raise InstallError
    #   · Issue #5595 · pypa/pipenv
    #   https://github.com/pypa/pipenv/issues/5595
    "coverage>=3.5.4",
    # The dlint less than 0.14.0 limits max version of flake8.
    # - dlint/requirements.txt at 0.13.0 · dlint-py/dlint
    #   https://github.com/dlint-py/dlint/blob/0.13.0/requirements.txt#L1
    "dlint>=0.14.0",
    # To the docformatter load pyproject.toml settings:
    "docformatter[tomli]; python_version < '3.11'",
    "docformatter; python_version >= '3.11'",
    "dodgy",
    # The hacking depends flake8 ~=6.1.0 or ~=5.0.1 or ~=4.0.1.
    # We should avoid the versions that is not compatible with the hacking,
    # considering the speed of dependency calculation process
    "flake8!=6.0.0,!=5.0.0,>=4.0.1",
    # To replace E501 in pycodestyle with B950 in flake8-bugbear:
    # - Using Black with other tools - Black 25.1.0 documentation
    #   https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#bugbear
    "flake8-bugbear",
    # To use flake8 --radon-show-closures
    "flake8-polyfill",
    # To use pyproject.toml for Flake8 configuration
    "Flake8-pyproject",
    # Latest hacking depends on legacy version of flake8, and legacy hacking doesn't narrow flake8 version.
    # When unpin hacking, it has possibility to install too legacy version of hacking.
    "hacking>=5.0.0; python_version >= '3.8'",
    "invokelint",
    # To enable 2 spaces indent list in mkdocs
    "mdx-truly-sane-lists",
    "mkdocs",
    "mypy",
    "pylint",
    "pytest",
    # see:
    # - fix: Replace `"` with `'` in user config template by andriihomiak · Pull Request #61 · hackebrot/pytest-cookies
    #   https://github.com/hackebrot/pytest-cookies/pull/61
    # - Fix windows tests by psobolewskiPhD · Pull Request #143 · napari/cookiecutter-napari-plugin
    #   https://github.com/napari/cookiecutter-napari-plugin/pull/143
    "pytest-cookies>=0.7.0",
    "pytest-mock",
    "pytest-resource-path",
    "pyvelocity; python_version >= '3.9'",
    "pyyaml",
    # Since the radon can't run when use pytest log format:
    # - Radon can't run when use pytest log fornat: `$()d` · Issue #251 · rubik/radon
    #   https://github.com/rubik/radon/issues/251
    "radon<6.0.0",
    "ruff",
    "semgrep; python_version>='3.9' or platform_system=='Linux'",
    "tox",
    "types-invoke",
    "types-setuptools",
    "xenon",
]

[project]
name = "cookiecutter-pypackage"
version = "0.2.0"
description = "Cookiecutter template for a Python package"
readme = "README.md"
# Dependency: setuptools>=61.0.0 requires Python 3.7
requires-python = ">=3.7"
license = {file = "LICENSE"}
keywords = ["cookiecutter", "template", "package"]
authors = [
    {name = "Sam Briggs", email = "briggySmalls90@gmail.com"}
]
maintainers = [
  {name = "Yukihiko Shinoda", email = "yuk.hik.future@gmail.com"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Software Development",
]
dependencies = [
    "cookiecutter",
]

[project.optional-dependencies]
test = []

[project.urls]
homepage = "https://github.com/briggySmalls/cookiecutter-pypackage"
# documentation = "https://readthedocs.org"
repository = "https://github.com/briggySmalls/cookiecutter-pypackage"
# changelog = "https://github.com/me/spam/blob/master/CHANGELOG.md"

[tool.bandit.assert_used]
skips = ["tests/*"]

[tool.bumpversion]
current_version = "0.2.0"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "invokelint/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'

[tool.coverage.report]
exclude_also = [
    # Assume `if TYPE_CHECKING: ... else: ...` block is covered · Issue #831 · nedbat/coveragepy
    #   https://github.com/nedbat/coveragepy/issues/831#issuecomment-517778185
    "if TYPE_CHECKING:",
    # Pylint will detect instead:
    # - abstract-method / W0223 - Pylint 2.17.0-dev0 documentation
    #   https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/abstract-method.html
    "raise NotImplementedError",
]

[tool.docformatter]
recursive = true
# For compatibility with Black
# - How to Configure docformatter — docformatter 1.7.5 documentation
#   https://docformatter.readthedocs.io/en/stable/configuration.html#a-note-on-options-to-control-styles
pre_summary_space = true
wrap-descriptions = 88
wrap-summaries = 88

[tool.flake8]
# Since B950 in flake8-bugbear detects lines that exceed max_line_length by more than 10%:
# - PyCQA/flake8-bugbear: A plugin for Flake8 finding likely bugs and design problems in your program. Contains warnings that don't belong in pyflakes and pycodestyle.
#   https://github.com/PyCQA/flake8-bugbear?tab=readme-ov-file#opinionated-warnings
# This setting follows the Black documentation in case when we use flake8-bugbear:
# - Using Black with other tools - Black 25.1.0 documentation
#   https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#bugbear
max_line_length = 80
extend_ignore = [
  # For compatibility with Black:
  # - Using Black with other tools - Black 25.1.0 documentation
  #   https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#bugbear
  "E203",
  "E501",
  "E701",
  # 2025-05-24 Now openstack/hacking wasn't introduced into Ruff and sorting imports is mainly considered with isort.
  "H306",
  # Cohesion may be in experimental.
  "H601",
]
statistics = true
show_source = true
exclude = [
  ".venv",
]

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = [
    "cookiecutter.*",
    "pytest_cookies.*",
]
ignore_missing_imports = true

[tool.pylint.basic]
# 2020-05-25 Yukihiko Shinoda
# I tried values in order started from 2,
# I felt that docstring is not useful until 6 while code keeps readable.
docstring-min-length = "7"

[tool.pylint.format]
max-line-length = 88

[tool.pylint.options]
# Since this rule against single responsibility principle.
# @see https://stackoverflow.com/questions/28722314/why-does-pylint-want-2-public-methods-per-class/40258006#40258006
min-public-methods = "1"

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
# To avoid to run test for {{cookiecutter.github_repository_name}}/tests .
testpaths = ["tests"]
log_cli = true
# log_cli_level = "DEBUG"
# log_format = "%(asctime)s %(process)d %(levelname)s %(name)s:%(filename)s:%(lineno)d %(message)s"

[tool.radon]
cc_min = "B"
show_complexity = true
show_mi = true

[tool.ruff]
line-length = 88
# To prevent:
#   WARNING: Error in file ./{{cookiecutter.github_repository_name}}/{{cookiecutter.project_slug}}/cli.py: Cannot parse file.
#   WARNING: Error in file ./{{cookiecutter.github_repository_name}}/tests/test_{{cookiecutter.project_slug}}.py: Cannot parse file.
extend-exclude = [
    "cli.py",
    "test_\\{\\{cookiecutter.project_slug}}.py",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    # lint.pydocstyle
    # Reason: Docstring may be missed since docstring-min-length is set.
    "D101",    # Missing docstring in public class
    "D102",    # Missing docstring in public method
    "D103",    # Missing docstring in public function
    "D105",    # Missing docstring in magic method
    "D106",    # Missing docstring in public nested class
    "D107",    # Missing docstring in __init__
    # Reason: First line may ends with function signature for expression.
    "D402",    # First line should not be the function’s “signature”
    # Reason: First line may ends with ":" for expression.
    "D415",    # First line should end with a period, question mark, or exclamation point
    # Reason: `Line too long` is checked by flake8-bugbear.
    "E501",    # Line too long ({width} > {limit})
]
fixable = [
    "COM812",  # Trailing comma missing
    "I",       # isort
    "PT001",   # Use `@pytest.fixture()` over `@pytest.fixture`
    "PT006",   # Wrong name(s) type in `@pytest.mark.parametrize`, expected `tuple`
    "SIM108",  # Use ternary operator `extra_context = {} if extra_context is None else request.param` instead of `if`-`else`-block
    "UP015",   # Unnecessary open mode parameters
    "UP032",   # Use f-string instead of `format` call
    "UP037",   # Remove quotes from type annotation
]

[tool.ruff.lint.isort]
# To follow H301: Do not import more than one module per line (*) in Flake8 + openstack/hacking
force-single-line = true

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.setuptools.packages.find]
include = ["hooks", "hooks.*"]
