on:
  push:
    branches:
      - main
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13'
      - run: uv sync
      # paambaati/codeclimate-action doesn't support major version tag.
      - uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: {{ "${{secrets.CC_TEST_REPORTER_ID}}" }}
        with:
          coverageCommand: uv run invoke test.coverage --xml
