on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: python -m pip install pipenv
      - run: python -m pipenv install --skip-lock --dev
      # MkDocs can't reference files above the docs directory
      # @see https://github.com/mkdocs/mkdocs/pull/1134#issuecomment-352904668
      - run: cp -fp README.md docs/index.md
      - run: python -m pipenv run mkdocs build
      - uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: yukihiko-shinoda/docs-cookiecutter-pypackage
          publish_branch: master
          publish_dir: ./site
