on:
  push:
    branches:
      - master
      - master-yukihiko-shinoda
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.14'
      - run: uv sync
      # MkDocs can't reference files above the docs directory
      # @see https://github.com/mkdocs/mkdocs/pull/1134#issuecomment-352904668
      - run: cp -fp README.md docs/index.md
      - run: uv run mkdocs build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: yukihiko-shinoda/docs-cookiecutter-pypackage
          publish_branch: master
          publish_dir: ./site
